/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}"
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        md: {
          background: { light: '#FFFBFE', dark: '#1C1B1F' },
          bg: { light: "#F3EDF7" },
          surface: { light: '#FFFBFE', dark: '#1C1B1F' },
          surfaceVariant: { light: '#E7E0EC', dark: '#49454F' },
          surfaceContainer: { high: { light: '#ECE6F0', dark: '#36343B' } },
          primary: { light: '#6750A4', dark: '#D0BCFF' },
          onPrimary: { light: '#FFFFFF', dark: '#381E72' },
          primaryContainer: { light: '#EADDFF', dark: '#4F378B' },
          onPrimaryContainer: { light: '#21005D', dark: '#EADDFF' },
          secondaryContainer: { light: '#E8DEF8', dark: '#4A4458' },
          onSecondaryContainer: { light: '#1D192B', dark: '#E8DEF8' },
          tertiary: { light: '#7D5260', dark: '#EFB8C8' },
          tertiaryContainer: { light: '#FFD8E4', dark: '#633B48' },
          onTertiaryContainer: { light: '#31111D', dark: '#FFD8E4' },
          error: { light: '#B3261E', dark: '#F2B8B5' },
          errorContainer: { light: '#F9DEDC', dark: '#8C1D18' },
          onErrorContainer: { light: '#410E0B', dark: '#F9DEDC' },
          onSurface: { light: '#1C1B1F', dark: '#E6E1E5' },
          onSurfaceVariant: { light: '#49454F', dark: '#CAC4D0' },
          outline: { light: '#79747E', dark: '#938F99' },
          'outline-variant': { light: '#CAC4D0', dark: '#49454F' },
          border: { light: '#CAC4D0', dark: '#938F99' },
        },
        primary: {
          DEFAULT: '#6750A4',
          container: '#EADDFF',
          onContainer: '#21005D',
        },
        secondary: {
          DEFAULT: '#625B71',
          container: '#E8DEF8',
          onContainer: '#1D192B',
        },
        tertiary: {
          DEFAULT: '#7D5260',
          container: '#FFD8E4',
          onContainer: '#31111D',
        },
        error: {
          DEFAULT: '#B3261E',
          container: '#F9DEDC',
          onContainer: '#410E0B',
        },
        background: {
          DEFAULT: '#FFFBFE',
          dark: '#1C1B1F',
        },
        surface: {
          DEFAULT: '#FFFBFE',
          dark: '#1C1B1F',
          variant: '#E7E0EC',
          variantDark: '#49454F',
        },
        outline: {
          DEFAULT: '#79747E',
          dark: '#938F99',
        },
        inverse: {
          surface: '#313033',
          onSurface: '#F4EFF4',
          primary: '#D0BCFF',
        },
        scrim: '#000000',
        shadow: '#000000',
        surfaceContainer: {
          lowest: '#FCF7FF',
          lowestDark: '#0F0D13',
          low: '#F7F2FA',
          lowDark: '#1D1B20',
          medium: '#F3EDF7',
          mediumDark: '#2B2930',
          high: '#ECE6F0',
          highDark: '#36343B',
          highest: '#E6E0E9',
          highestDark: '#413F47',
        },
        legacy: {
          bg: '#F3EDF7',
          bgDark: '#2B2930',
          surfaceInput: '#E7E0EC',
          surfaceInputDark: '#49454F',
          text: '#1D1B20',
          textDark: '#E6E1E5',
          accent: '#6750A4',
          accentDark: '#D0BCFF',
          border: '#CAC4D0',
          borderDark: '#938F99',
        },
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '28px',
        'full': '9999px',
      },
      boxShadow: {
        'md3-0': '0px 0px 0px 0px rgba(0,0,0,0.2), 0px 0px 0px 0px rgba(0,0,0,0.14), 0px 0px 0px 0px rgba(0,0,0,0.12)',
        'md3-1': '0px 1px 3px 1px rgba(0,0,0,0.15), 0px 1px 2px 0px rgba(0,0,0,0.3)',
        'md3-2': '0px 2px 6px 2px rgba(0,0,0,0.15), 0px 1px 2px 0px rgba(0,0,0,0.3)',
        'md3-3': '0px 4px 8px 3px rgba(0,0,0,0.15), 0px 1px 3px 0px rgba(0,0,0,0.3)',
        'md3-4': '0px 6px 10px 4px rgba(0,0,0,0.15), 0px 2px 3px 0px rgba(0,0,0,0.3)',
        'md3-5': '0px 8px 12px 6px rgba(0,0,0,0.15), 0px 4px 4px 0px rgba(0,0,0,0.3)',
      },
      fontFamily: {
        'display-large': ['system-ui', 'sans-serif'],
        'display-medium': ['system-ui', 'sans-serif'],
        'display-small': ['system-ui', 'sans-serif'],
        'headline-large': ['system-ui', 'sans-serif'],
        'headline-medium': ['system-ui', 'sans-serif'],
        'headline-small': ['system-ui', 'sans-serif'],
        'title-large': ['system-ui', 'sans-serif'],
        'title-medium': ['system-ui', 'sans-serif'],
        'title-small': ['system-ui', 'sans-serif'],
        'label-large': ['system-ui', 'sans-serif'],
        'label-medium': ['system-ui', 'sans-serif'],
        'label-small': ['system-ui', 'sans-serif'],
        'body-large': ['system-ui', 'sans-serif'],
        'body-medium': ['system-ui', 'sans-serif'],
        'body-small': ['system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-medium': ['45px', { lineHeight: '52px' }],
        'display-small': ['36px', { lineHeight: '44px' }],
        'headline-large': ['32px', { lineHeight: '40px' }],
        'headline-medium': ['28px', { lineHeight: '36px' }],
        'headline-small': ['24px', { lineHeight: '32px' }],
        'title-large': ['22px', { lineHeight: '28px' }],
        'title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'md-display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'md-display-medium': ['45px', { lineHeight: '52px' }],
        'md-display-small': ['36px', { lineHeight: '44px' }],
        'md-headline-large': ['32px', { lineHeight: '40px' }],
        'md-headline-medium': ['28px', { lineHeight: '36px' }],
        'md-headline-small': ['24px', { lineHeight: '32px' }],
        'md-title-large': ['22px', { lineHeight: '28px' }],
        'md-title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'md-title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'md-label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'md-label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'md-label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'md-body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'md-body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'md-body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
      },
    },
  },
  plugins: [],
};
